

const TIPO_INSTRUCCION = {

    DECLARACIONV: 'DECLARACIONV',
    ARITMETICA: 'ARITMETICA',
    ASIGNACIONV: 'ASIGNACIONV',
    COLUMNA: 'COLUMNA',
    CREATET: 'CREATET',
    AGREGARC: 'AGREGARC',
    ELIMINARC: 'ELIMINARC',
    RENAMET: 'RENAMET',
    RENAMEC: 'RENAMEC',
    ELIMINART: 'ELIMINART',
    INSERT: 'INSERT',
    SELECTS: 'SELECTS',
    SELECTV: 'SELECTV',
    UPDATE: 'UPDATE',
    TRUNCATE: 'TRUNCATE',
    DELETE: 'DELETE',
    BEGINEND: 'BEGINEND',
    SI: 'SI',
    CASO: 'CASO',
    CUANDO: 'CUANDO',
    MIENTRAS: 'MIENTRAS',
    PARA: 'PARA',
    BREAK: 'BREAK',
    CONTINUE: 'CONTINUE',
    FUNCION: 'FUNCION',
    PARAMETRO: 'PARAMETRO',
    DEVOLVER : 'DEVOLVER',
    METODO: 'METODO',
    LLAMADA: 'LLAMADA',
    PRINT : 'PRINT',
    LOWER: 'LOWER',
    UPPER: 'UPPER',
    LEN: 'LEN',
    ROUND: 'ROUND',
    TRUNCATES: 'TRUNCATES',
    TYPEOF: 'TYPEOF',
    LLAMADAS: 'LLAMADAS'





}

module.exports = TIPO_INSTRUCCION
